# Generated by Django 4.0.2 on 2023-05-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donepl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='home_address',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=250),
        ),
    ]
