# Generated by Django 4.2.1 on 2023-05-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donepl", "0005_alter_customer_user_alter_worker_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
