# Generated by Django 4.2.1 on 2023-05-22 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donepl", "0007_alter_customer_home_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="rating",
            field=models.FloatField(
                default=5.0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(3.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="services",
            field=models.ManyToManyField(blank=True, null=True, to="donepl.service"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="phone_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="rating",
            field=models.FloatField(
                default=5.0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(3.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="services",
            field=models.ManyToManyField(blank=True, null=True, to="donepl.service"),
        ),
    ]
