# Generated by Django 4.2.1 on 2023-05-22 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("donepl", "0008_alter_customer_phone_number_alter_customer_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
