# Generated by Django 4.2.1 on 2023-05-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donepl", "0009_alter_worker_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="name",
        ),
    ]
