# Generated by Django 4.2.1 on 2023-05-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donepl", "0010_remove_service_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="service",
            name="date_accepted",
        ),
        migrations.RemoveField(
            model_name="service",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="service",
            name="order_time",
        ),
        migrations.AddField(
            model_name="service",
            name="name",
            field=models.CharField(
                choices=[
                    ("House Cleaning", "House Cleaning"),
                    ("Handy Man", "Maintenance requests"),
                    (
                        "Car Cleaning",
                        "Car cleaning services, available at gas station points or by your house",
                    ),
                    ("Kitchen cleaning", "Kitchen cleaning services"),
                    ("Bath Cleaning", "Bath cleaning services"),
                    ("Window Cleaning", "Window cleaning services"),
                    ("Garage Cleaning", "Garage cleaning services"),
                    ("Cooking", "Cooking"),
                    ("Clothes Washing", "Clothes Washing"),
                    ("Dog Walking", "Dog Walking"),
                    ("Pet Feeding", "Pet Feeding"),
                    ("Dishwashing", "Dishwashing"),
                    ("Lawn Mowing", "Lawn Mowing"),
                    ("Plants Watering", "Plants Watering"),
                ],
                default="House Cleaning",
                max_length=200,
            ),
        ),
    ]
