# Generated by Django 4.2.1 on 2023-05-29 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("donepl", "0011_remove_service_cost_remove_service_date_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="services",
            field=models.ManyToManyField(blank=True, to="donepl.service"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="services",
            field=models.ManyToManyField(blank=True, to="donepl.service"),
        ),
    ]
