# Generated by Django 4.2.1 on 2023-06-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donepl", "0012_service_user_alter_customer_services_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cost",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_rating",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name="order",
            name="hours",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="worker_rating",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
