# Generated by Django 4.2.1 on 2023-06-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donepl", "0013_alter_order_cost_alter_order_customer_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="location",
        ),
    ]
